version: '3.9'
networks:
  green-era-network:
    driver: bridge

volumes:
  pg_user_data:
  pg_booking_data:
  pg_gardener_data:

services:
  # ------------------- DISCOVERY SERVICE -------------------
  discovery-service:
    image: 211888003693.dkr.ecr.ap-southeast-2.amazonaws.com/discovery-service
#    container_name: discovery-service
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - green-era-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ------------------- USER SERVICE DB -------------------
  postgres-user:
    image: postgres:15
#    container_name: postgres-user
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
#    ports:
#      - "5432:5432"
    volumes:
      - pg_user_data:/var/lib/postgresql/data
    networks:
      - green-era-network

  # ------------------- BOOKING SERVICE DB -------------------
  postgres-booking:
    image: postgres:15
#    container_name: postgres-booking
    environment:
      POSTGRES_DB: booking_db
      POSTGRES_USER: booking
      POSTGRES_PASSWORD: booking
#    ports:
#      - "5433:5432"
    volumes:
      - pg_booking_data:/var/lib/postgresql/data
    networks:
      - green-era-network

  # ------------------- GARDENER SERVICE DB -------------------
  postgres-gardener:
    image: postgres:15
#    container_name: postgres-gardener
    environment:
      POSTGRES_DB: gardener_db
      POSTGRES_USER: gardener
      POSTGRES_PASSWORD: gardener
#    ports:
#      - "5434:5432"
    volumes:
      - pg_gardener_data:/var/lib/postgresql/data
    networks:
      - green-era-network

  # ------------------- USER SERVICE -------------------
  user-service:
    image: 211888003693.dkr.ecr.ap-southeast-2.amazonaws.com/user-service
#    container_name: user-service
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      postgres-user:
        condition: service_started
      discovery-service:
        condition: service_healthy
    networks:
      - green-era-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  # ------------------- BOOKING SERVICE -------------------
  booking-service:
    image: 211888003693.dkr.ecr.ap-southeast-2.amazonaws.com/booking-service
#    container_name: booking-service
    build:
      context: ./booking-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      postgres-booking:
        condition: service_started
      discovery-service:
        condition: service_healthy
    networks:
      - green-era-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  # ------------------- GARDENER SERVICE -------------------
  gardener-service:
    image: 211888003693.dkr.ecr.ap-southeast-2.amazonaws.com/gardener-service
#    container_name: gardener-service
    build:
      context: ./gardener-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      postgres-gardener:
        condition: service_started
      discovery-service:
        condition: service_healthy
    networks:
      - green-era-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  # ------------------- GATEWAY SERVICE -------------------
  gateway-service:
    image: 211888003693.dkr.ecr.ap-southeast-2.amazonaws.com/gateway-service
#    container_name: gateway-service
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    depends_on:
      user-service:
        condition: service_started
      booking-service:
        condition: service_started
      gardener-service:
        condition: service_started
      discovery-service:
        condition: service_healthy
    networks:
      - green-era-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker